In [0]:
#!pip3 install torch  --> command to install pytorch

WHAT IS PYTORCH?

It’s a Python-based scientific computing package targeted at two sets of audiences:

1.   a deep learning research platform that provides maximum flexibility and speed

2.   A replacement for NumPy to use the power of GPUs

In [0]:
import torch     # command to import pytorch
import numpy as np
from matplotlib import pyplot as plt

A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.  a tensor variable can be initialised using .tensor() function

In [0]:
v=torch.tensor([1,2,3,4,6,7,1])
print(v)

tensor([1, 2, 3, 4, 6, 7, 1])


In [0]:
print(v.dtype)
print(v[2])   # single selection of tensor element
print(v[1:4])  # multiple selection of tensor element

torch.int64
tensor(3)
tensor([2, 3, 4])


In [0]:
v2=torch.FloatTensor([3,4,5,6,7])  # generates tensor variable with float datatype

In [0]:
print(v2.dtype)

torch.float32


In [0]:
v2.size()   # to detemine the number of element in the tensor

torch.Size([5])

In [0]:
v2.view(5,1)    # Reshapes the tensor variable

tensor([[3.],
        [4.],
        [5.],
        [6.],
        [7.]])

In [0]:
a=np.array([3,4,6,5])              
tens=torch.from_numpy(a)    # converts numpy array to tensor
print(tens)
print(tens.type())

tensor([3, 4, 6, 5])
torch.LongTensor


In [0]:
num=tens.numpy()     # converts tensor to numpy array
print(num)

[3 4 6 5]


In [0]:
a1 = torch.randn(1, 3)
a2 = torch.randn(1, 3)

In [0]:
print("a1",a1)
print("a2",a2)
print(a1+a2)     # we can also perform mathematical operations on tensor valiables
print(a1*2)

a1 tensor([[0.0521, 0.3010, 0.9908]])
a2 tensor([[-0.4768, -0.9299,  0.5342]])
tensor([[-0.4247, -0.6289,  1.5250]])
tensor([[0.1043, 0.6020, 1.9816]])


In [0]:
x=torch.linspace(1,10,100)   # Generates a list of values from 1 to 10 of step size 100
y=torch.exp(x)
plt.plot(x.numpy(),y.numpy())  # REMEMBER: To convert the tensor datatype to numpy so that we can plot the data

In [0]:
one_dim=torch.arange(6)   #  Generates a one dimensional tensor array
print(one_dim)

tensor([0, 1, 2, 3, 4, 5])


In [0]:
two_dim=one_dim.view(3,2)  # Resphapes the one dimensional tensor array to a two dimensional tensor array
print(two_dim)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [0]:
print(two_dim.dim())
print(two_dim[2,0])    # selects the element in the second row and zeroth column (the row/column count starts from zero)

2
tensor(4)


In [0]:
three_dim=torch.arange(18).view(3,3,2)  # aranges 18 elements to a three dimensional tensor array
print(three_dim.dim())
print(three_dim)

3
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])


In [0]:
three_dim[1,2,1]   # here the first element correnspond to the block matrix and the second and third number corresponds to the row and column value of that block matrix.

tensor(11)

In [0]:
three_dim[2,0:3,0:2]  # selects all the rows and columns of the second block

tensor([[12, 13],
        [14, 15],
        [16, 17]])

In [0]:
mat_a=torch.tensor([2,3,4,5,6,7]).view(3,2)
print(mat_a)

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [0]:
mat_b=torch.tensor([3,4,5,1,2,7]).view(2,3)
print(mat_b)

tensor([[3, 4, 5],
        [1, 2, 7]])


In [0]:
print(torch.matmul(mat_a,mat_b))  # performs matrix multiplication on tensor matrix

tensor([[ 9, 14, 31],
        [17, 26, 55],
        [25, 38, 79]])


AUTOGRAD:
Autograd is now a core torch package for automatic differentiation. It uses a tape based system for automatic differentiation.
In autograd, if any input Tensor of an operation has requires_grad=True, the computation will be tracked. After computing the backward pass, a gradient w.r.t. this tensor is accumulated into .grad attribute.

In [0]:
x1=torch.tensor(2.0,requires_grad=True)  
y1=9*x**4+2*x**3+3*x**2+6*x+1
y1.backward()
x1.grad

In [0]:
z.grad

tensor(12.)

In [0]:
x=torch.tensor(1.0,requires_grad=True)
z=torch.tensor(2.0,requires_grad=True)
print("X:",x,"Z:",z)


X: tensor(1., requires_grad=True) Y: tensor(9., grad_fn=<AddBackward0>)


tensor(2.)

In the below equation, 

In [0]:
y=x**2+z**3
y.backward()
x.grad

tensor(8.)