# Count Vectorizer

In [5]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer

In [43]:
data=["Machine learning is a subfield of artificial intelligence.","Machine learning is a continuously developing field.","Any technology user today has benefitted from machine learning."]

In [44]:
data

['Machine learning is a subfield of artificial intelligence.',
 'Machine learning is a continuously developing field.',
 'Any technology user today has benefitted from machine learning.']

First we create an instance of count vectorizer. Some of the arguments that can be passed to create an instance of the count vectorizer are:- ngram_range:tuple(min,max) :: Sets the lower and upper boundary of the ngrams to be extracted from the text. max_features:: considers only the top maximum features of the text 

In [58]:
vect=CountVectorizer()

To create the vectorizer, we have to fit the instance with the data/corpous

In [60]:
vect.fit(data)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

.vocabulary_ attribute is a mapping of the terms and indexes

In [61]:
print(vect.vocabulary_)

{'machine': 11, 'learning': 10, 'is': 9, 'subfield': 13, 'of': 12, 'artificial': 1, 'intelligence': 8, 'continuously': 3, 'developing': 4, 'field': 5, 'any': 0, 'technology': 14, 'user': 16, 'today': 15, 'has': 7, 'benefitted': 2, 'from': 6}


In [68]:
print(vect.vocabulary_)

{'machine': 11, 'learning': 10, 'is': 9, 'subfield': 13, 'of': 12, 'artificial': 1, 'intelligence': 8, 'continuously': 3, 'developing': 4, 'field': 5, 'any': 0, 'technology': 14, 'user': 16, 'today': 15, 'has': 7, 'benefitted': 2, 'from': 6}


The fitted vocabulary is transformed to a vector using the below function

In [63]:
data_transformed=vect.transform(data)

In [64]:
data_transformed.toarray()

array([[0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1]], dtype=int64)

We can also get a transform vector consisting of only selected selected words

In [65]:
vect.transform(['Machine','learning']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int64)

The above steps can also be executed in one command using the below mentioned command.

In [66]:
vect.fit_transform(data).toarray()

array([[0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1]], dtype=int64)